### ISSUE TITLE
show my list of guests

### ISSUE THREAD

**Issue by buritica** [colombia-dev/leonel#10]

**Comment by julianduque** [comment]
do we want owners/admins to get the list of others guests? like:

`@leonel invitados julianduque`

**Comment by buritica** [comment]
Yes, I think that's a good idea. We'd have to extend the seed script to add the is_owner property, and make sure that we're not overriding the guests array now that it exists. I was thinking about adding a few tests to that seed script too, perhaps rename to migration or something
