### ISSUE TITLE
Equivocación en email de invitación

### ISSUE THREAD

**Issue by cronopio** [colombia-dev/leonel#108]
> me quedo mal escritp el correo para una invitación. Hay manera de cancelar esa invitación, o ya debo esperar hasta el otro mes?

https://colombia-dev.slack.com/archives/C03DP984H/p1536939518000100

Abro el issue para no perder este mensaje en el historial del slack. Un miembro de la comunidad dice haberse equivocado en el email de invitación. Al parecer no hay tal escenario en el código entonces podemos evaluar aquí entre todos posibles soluciones.

Por ahora la simple y fácil el compañero tendrá que esperar al próximo mes cuando se reseteen las invitaciones.

Pero de pronto la API de slack nos permita "cancelar" esa invitación y revertir el conteo de invitaciones al usuario nuevamente? Si alguien tiene mas info o me puede compartir enlaces para seguir investigando se lo agradezco.

**Comment by niczapata** [comment]
Hola, como consejo te recomendaría pedírselo a la página de ellos buscando en su blog o en la página de "Sobre nosotros". Eso me ayudó con un problema con una página que me registré por accidente y les pedí que me eliminaran la cuenta y pues funcionó, espero que te pueda ayudar, no soy muy experto en lo que te dedicas, te cuento mi experiencia en este tipo de casos, Gracias y que ojalá te vaya bien.


________________________________
De: Daniel Aristizabal <notifications@github.com>
Enviado: viernes, 14 de septiembre de 2018 11:10 a.m.
Para: colombia-dev/leonel
Cc: Subscribed
Asunto: [colombia-dev/leonel] Equivocación en email de invitación (#108)


me quedo mal escritp el correo para una invitación. Hay manera de cancelar esa invitación, o ya debo esperar hasta el otro mes?

https://colombia-dev.slack.com/archives/C03DP984H/p1536939518000100

Abro el issue para no perder este mensaje en el historial del slack. Un miembro de la comunidad dice haberse equivocado en el email de invitación. Al parecer no hay tal escenario en el código entonces podemos evaluar aquí entre todos posibles soluciones.

Por ahora la simple y fácil el compañero tendrá que esperar al próximo mes cuando se reseteen las invitaciones.

Pero de pronto la API de slack nos permita "cancelar" esa invitación y revertir el conteo de invitaciones al usuario nuevamente? Si alguien tiene mas info o me puede compartir enlaces para seguir investigando se lo agradezco.

**Comment by buritica** [comment]
@cronopio ya le di una invitacion nueva a Alvaro
