### ISSUE TITLE
add master key "BairesDev"

### ISSUE THREAD

**Issue by jessecogollo** [colombia-dev/leonel#36]
When somebody writes "bairesDev" Leonel should response with a little resume about them.

**Comment by buritica** [comment]
What should the response be? I can probably add this over the weekend

**Comment by yefb** [comment]
I'd give a quick summary of the mixed feelings most of the developers have with them.
- Their Spamming bot (which they never fix)
- Their unresponsiveness
- The fact that we have around a couple devs in our community that have worked with them (good experience), which corresponds to a very small percentage in comparison of the complaints we get every week about them

That's pretty much my proposal.

**Comment by josuedanielbust** [comment]
@yefb This? ( Check pull request #57 )

**Comment by yefb** [comment]
@JosueDanielBust 😍

**Comment by buritica** [comment]
we've decided not to have an official community position on them, we're closing this issue for this reason
