### ISSUE TITLE
Add command to see this repository's URL

### ISSUE THREAD

**Issue by jonathansotoan** [colombia-dev/leonel#39]
When chatting directly to Leonel; if someone writes "¿Dónde estás?", "Where are you?" or "source"; he should answer with this URL: https://github.com/colombia-dev/leonel

**Comment by buritica** [comment]
<img width="706" alt="screen shot 2017-04-06 at 8 39 10 pm" src="https://cloud.githubusercontent.com/assets/228120/24782007/1deab9c2-1b09-11e7-9f54-14059e664b2b.png">
